FROM dorowu/ubuntu-desktop-lxde-vnc

#RUN curl -Ok https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
#RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p

#RUN echo 'export PATH="~/home/ubuntu/miniconda3:$PATH"' >> ~/.bashrc


RUN curl -Ok https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
RUN bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p
RUN rm Anaconda3-5.0.1-Linux-x86_64.sh

ENV PATH "$PATH:/home/ubuntu/anaconda3/bin"

RUN conda update conda
#RUN conda install -c conda-forge geopandas
RUN conda install -c conda-forge opencv
RUN conda install -c plotly plotly
RUN conda install -c anaconda csvkit
RUN conda install -c anaconda boto

RUN apt-get update

RUN conda install -c conda-forge osmnx

#RUN pip install geopandas


COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN apt-get -y install qgis python-qgis
RUN apt-get -y install jq

#COPY . .
